image: docker:latest

stages:
  - build

services:
- docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker info

build:
  stage: build
  artifacts:
    paths:
      - public
  script:
  - for i in $(ls);do docker build -t registry.gitlab.com/rdes/$i:latest .; done
  - for i in $(ls);do docker push registry.gitlab.com/rdes/$i:latest; done
